version: '3'
services: 
    nginx_app:
        image: nginx:latest
        depends_on: 
          - flask_app
        volumes: 
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
          - 8080:80
        networks:
          - normal_network
    flask_app:
        build: 
            context: ./app/
            dockerfile: Dockerfile
        expose:
          - 5000
        depends_on: 
          - redis_app
        networks: 
          - normal_network
    redis_app:
        image: redis:latest
        expose:
          - 6379
        networks: 
          - normal_network
networks: 
    normal_network:
        external: true

