version: "3.9"
services:
  nginx-static:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    volumes: 
      - ./data:/srv
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 90:90
  nginx_app:
    build:
      context: ./nginx-proxy/
      dockerfile: Dockerfile
    volumes:
      - ./nginx-proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - flask_app
    ports:
      - 8080:80
  flask_app:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"